spring.application.name=service
spring.datasource.url=jdbc:postgresql://localhost:5432/sbnz
spring.datasource.username=postgres
spring.datasource.password=hladannes1512
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true