package com.ftn.sbnz.model.decision;

public enum FinalState {

    // BURNOUT
    EARLY_BURNOUT_PATTERN,
    BURNOUT_SYNDROME,
    SEVERE_BURNOUT_STATE,

    // ANXIETY
    ANXIETY_RISK_PATTERN,
    ANXIETY_ESCALATION_STATE,
    PANIC_ATTACK_PATTERN,
    GENERALIZED_ANXIETY_TENDENCY,

    // DEPRESSION
    DEPRESSIVE_PATTERN,
    EMOTIONAL_NUMBNESS_STATE,
    SEVERE_DEPRESSIVE_RISK_PATTERN,

    // COGNITIVE
    MENTAL_FATIGUE_SYNDROME,
    DECISION_FATIGUE_STATE,

    // SOCIAL
    SOCIAL_WITHDRAWAL_SYNDROME,
    INTERPERSONAL_DETACHMENT_PATTERN,
    SOCIAL_ISOLATION_PROGRESSION,

    // CRITICAL
    SEVERE_PSYCHOLOGICAL_DETERIORATION,
    EMOTIONAL_COLLAPSE_RISK,
    SELF_HARM_RISK_PATTERN,
    CRISIS_INTERVENTION_RECOMMENDED
}
