import com.ftn.sbnz.model.assessment.UserAssessmentEvent;
global com.ftn.sbnz.service.services.FeatureCalculatorService featureService;
import com.ftn.sbnz.model.events.*;
import java.time.LocalDateTime;
import java.util.List;

declare UserAssessmentEvent
    @role(event)
    @timestamp(timestampMillis)
end
declare StressEscalationEvent @role(event) @timestamp(timestampMillis) end
declare BurnoutEmergenceEvent @role(event) @timestamp(timestampMillis) end
declare EmotionalVolatilityBurstEvent @role(event) @timestamp(timestampMillis) end
declare CognitiveDegradationEvent @role(event) @timestamp(timestampMillis) end
declare SocialCollapseEvent @role(event) @timestamp(timestampMillis) end
declare CrisisBuildUpEvent @role(event) @timestamp(timestampMillis) end

rule "Stress escalation event"
salience 100
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(72h),
        collectList($e)
    )
    $score : Double() from featureService.calculateStressEscalationScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not StressEscalationEvent(userId == $uid)
then
    insert(new StressEscalationEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Stress Escalation za " + $uid + " | Score: " + $score);
end

rule "Burnout emergence event"
salience 70
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(7d),
        collectList($e)
    )
    $score : Double() from featureService.calculateBurnoutEmergenceScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not BurnoutEmergenceEvent(userId == $uid)
then
    insert(new BurnoutEmergenceEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Burnout rizik detektovan za " + $uid + " | Score: " + $score);
end

rule "Emotional volatility burst"
salience 80
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(24h),
        collectList($e)
    )
    $score : Double() from featureService.calculateEmotionalVolatilityBurstScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not EmotionalVolatilityBurstEvent(userId == $uid)
then
    insert(new EmotionalVolatilityBurstEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Volatility burst detektovan za " + $uid + " | Score: " + $score);
end

rule "Cognitive degradation event"
salience 60
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(7d),
        collectList($e)
    )
    $score : Double() from featureService.calculateCognitiveDegradationScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not CognitiveDegradationEvent(userId == $uid)
then
    insert(new CognitiveDegradationEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Detektovano kognitivno propadanje za " + $uid + " | Score: " + $score);
end

rule "Social collapse trajectory"
salience 50
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(7d),
        collectList($e)
    )
    $score : Double() from featureService.calculateSocialCollapseScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not SocialCollapseEvent(userId == $uid)
then
    insert(new SocialCollapseEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Detektovana socijalna kolaps putanja za " + $uid + " | Score: " + $score);
end

rule "Crisis buildup event"
salience 40
when
    $t0 : UserAssessmentEvent($uid : assessment.userId)
    $events : List() from accumulate(
        $e : UserAssessmentEvent(assessment.userId == $uid) over window:time(72h),
        collectList($e)
    )
    $score : Double() from featureService.calculateCrisisBuildUpScore($t0, $events)
    eval($score.doubleValue() >= 0.0)
    not CrisisBuildUpEvent(userId == $uid)
then
    insert(new CrisisBuildUpEvent($uid, LocalDateTime.now(), $score.doubleValue()));
    System.out.println("Detektovana kriza u nastajanju za " + $uid + " | Score: " + $score);
end
