package rules;
import com.ftn.sbnz.model.features.*;
import com.ftn.sbnz.model.risks.*;

rule "Sleep Disturbance Risk"
when
    SleepFeatures( $sqi : SQI, $sfi : SFI, SQI >= 0.3 && SQI < 0.6, SFI >= 0.3 && SFI < 0.6 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setSleepDisturbanceRisk(true);
    risk.setScore(($sqi + $sfi) / 2.0);
    insert(risk);
end

rule "Sleep Deprivation Risk"
when
    SleepFeatures( $sqi : SQI, $sfi : SFI, SQI < 0.3, SFI >= 0.6 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setSleepDeprivationRisk(true);
    risk.setScore(($sqi + $sfi) / 2.0);
    insert(risk);
end

rule "Cognitive Strain Risk"
when
    CognitiveFeatures( $cli : CLI, $mfs : MFS, CLI >= 0.3 && CLI < 0.6, MFS >= 0.3 && MFS < 0.6 )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setCognitiveStrainRisk(true);
    risk.setScore(($cli + $mfs) / 2.0);
    insert(risk);
end

rule "Cognitive Overload Risk"
when
    CognitiveFeatures( $cli : CLI, $mfs : MFS, CLI >= 0.6, MFS >= 0.6 )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setCognitiveOverloadRisk(true);
    risk.setScore(($cli + $mfs) / 2.0);
    insert(risk);
end

rule "Decision Impairment Risk"
when
    CognitiveFeatures( $dli : DLI, $cli : CLI, DLI >= 0.6, CLI >= 0.6 )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setDecisionImpairmentRisk(true);
    risk.setScore(($dli + $cli) / 2.0);
    insert(risk);
end

rule "Social Withdrawal Risk"
when
    SocialFeatures( $swi : SWI, $sad : SAD, SWI >= 0.3 && SWI < 0.6, SAD >= 0.3 && SAD < 0.6 )
then
    SocialRisks risk = new SocialRisks();
    risk.setSocialWithdrawalRisk(true);
    risk.setScore(($swi + $sad) / 2.0);
    insert(risk);
end

rule "Social Isolation Risk"
when
    SocialFeatures( $swi : SWI, $sad : SAD, SWI >= 0.6, SAD >= 0.6 )
then
    SocialRisks risk = new SocialRisks();
    risk.setSocialIsolationRisk(true);
    risk.setScore(($swi + $sad) / 2.0);
    insert(risk);
end

rule "Interpersonal Detachment Risk"
when
    SocialFeatures( $idi : IDI, $swi : SWI, IDI >= 0.6, SWI >= 0.6 )
then
    SocialRisks risk = new SocialRisks();
    risk.setInterpersonalDetachmentRisk(true);
    risk.setScore(($idi + $swi) / 2.0);
    insert(risk);
end

rule "Stress Progression Risk"
when
    TemporalFeatures( $dr : DR, $evl : EVL, DR >= 0.6, EVL >= 0.6 )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setStressProgressionRisk(true);
    risk.setScore(($dr + $evl) / 2.0);
    insert(risk);
end

rule "Chronic Deterioration Risk"
when
    TemporalFeatures( $sps : SPS, $dr : DR, SPS >= 0.6, DR >= 0.6 )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setDeteriorationRisk(true);
    risk.setScore(($sps + $dr) / 2.0);
    insert(risk);
end


