//EMOTIONAL RISKS
rule "Emotional Stress Risk"
when
   EmotionalFeatures( $f : this )
    eval( ($f.getESI() >= 0.3 && $f.getESI() < 0.6)  || ($f.getNAI() >= 0.3 && $f.getNAI() < 0.6) )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalStressRisk(true);
    insert(risk);
end
rule "Emotional Overload Risk"
when
    EmotionalFeatures( ESI >= 0.6, LCI >= 0.3 && LCI < 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalOverloadRisk(true);
    insert(risk);
end
rule "Emotional Instability Risk"
when
    EmotionalFeatures( ESI >= 0.6, EVI >= 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalInstabilityRisk(true);
    insert(risk);
end
rule "Severe Emotional Crisis Risk"
when
    EmotionalFeatures( ESI >= 0.8, NAI >= 0.6, LCI >= 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalCrisisRisk(true);
    insert(risk);
end
//PHYSICAL RISKS
rule "Sleep Disturbance Risk"
when
    SleepFeatures( SQI >= 0.3 && SQI < 0.6,
                   SFI >= 0.3 && SFI < 0.6 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setSleepDisturbanceRisk(true);
    insert(risk);
end
rule "Sleep Deprivation Risk"
when
    SleepFeatures( SQI < 0.3,
                   SFI >= 0.6 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setSleepDeprivationRisk(true);
    insert(risk);
end
rule "Physical Fatigue Risk"
when
    SleepFeatures( FI >= 0.6,
                      SQI < 0.3 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setPhysicalFatigueRisk(true);
    insert(risk);
end
rule "Exhaustion Syndrome Risk"
when
    SleepFeatures( FI >= 0.6,
                      SFI >= 0.6,
                      SQI < 0.3 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setExhaustionSyndromeRisk(true);
    insert(risk);
end
//COGNITIVE RISKS
rule "Cognitive Strain Risk"
when
    CognitiveFeatures(
        CLI >= 0.3 && CLI < 0.6,
        MFS >= 0.3 && MFS < 0.6
    )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setCognitiveStrainRisk(true);
    insert(risk);
end
rule "Cognitive Overload Risk"
when
    CognitiveFeatures(
        CLI >= 0.6,
        MFS >= 0.6
    )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setCognitiveOverloadRisk(true);
    insert(risk);
end
rule "Decision Impairment Risk"
when
    CognitiveFeatures(
        DLI >= 0.6,
        CLI >= 0.6
    )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setDecisionImpairmentRisk(true);
    insert(risk);
end
rule "Mental Fatigue Risk"
when
    CognitiveFeatures(
        MFS >= 0.6
    )
    SleepFeatures(
        FI >= 0.6
    )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setMentalFatigueRisk(true);
    insert(risk);
end
//SOCIAL RISKS
rule "Social Withdrawal Risk"
when
    SocialFeatures(
        SWI >= 0.3 && SWI < 0.6,
        SAD >= 0.3 && SAD < 0.6
    )
then
    SocialRisks risk = new SocialRisks();
    risk.setSocialWithdrawalRisk(true);
    insert(risk);
end
rule "Social Isolation Risk"
when
    SocialFeatures(
        SWI >= 0.6,
        SAD >= 0.6
    )
then
    SocialRisks risk = new SocialRisks();
    risk.setSocialIsolationRisk(true);
    insert(risk);
end
rule "Interpersonal Detachment Risk"
when
    SocialFeatures(
        IDI >= 0.6,
        SWI >= 0.6
    )
then
    SocialRisks risk = new SocialRisks();
    risk.setInterpersonalDetachmentRisk(true);
    insert(risk);
end
rule "Behavioral Withdrawal Risk"
when
    SocialFeatures(
        SAD >= 0.6
    )

    CognitiveFeatures(
        CLI >= 0.6
    )
then
    SocialRisks risk = new SocialRisks();
    risk.setBehavioralWithdrawalRisk(true);
    insert(risk);
end
//ENVIRONMENTAL RISKS
rule "External Pressure Risk"
when
    EnvironmentalFeatures(
        ESL >= 0.3 && ESL < 0.6
    )

    EmotionalFeatures(
        ESI >= 0.3 && ESI < 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setExternalPressureRisk(true);
    insert(risk);
end

rule "High External Stress Risk"
when
    EnvironmentalFeatures(
        ESL >= 0.6
    )

    EmotionalFeatures(
        ESI >= 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setHighExternalStressRisk(true);
    insert(risk);
end

rule "Chronic Stress Exposure Risk"
when
    EnvironmentalFeatures(
        CSE >= 0.6
    )

    TemporalFeatures(
        SPS >= 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setChronicStressExposureRisk(true);
    insert(risk);
end
//TEMPORAL RISKS
rule "Stress Progression Risk"
when
    TemporalFeatures(
        DR >= 0.6,
        EVL >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setStressProgressionRisk(true);
    insert(risk);
end

rule "Emotional Instability Temporal Risk"
when
    TemporalFeatures(
        TII >= 0.6
    )

    EmotionalFeatures(
        EVI >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setEmotionalInstabilityTemporalRisk(true);
    insert(risk);
end

rule "Chronic Deterioration Risk"
when
    TemporalFeatures(
        SPS >= 0.6,
        DR >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setChronicDeteriorationRisk(true);
    insert(risk);
end

rule "Rapid Escalation Risk"
when
    TemporalFeatures(
        EVL >= 0.6
    )

    EmotionalFeatures(
        ESI >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setRapidEscalationRisk(true);
    insert(risk);
end