package rules;
import com.ftn.sbnz.model.risks.*;
import com.ftn.sbnz.model.patterns.*;
import com.ftn.sbnz.model.decision.*;
import java.util.List;

rule "Self Harm Final Decision"
when
    CriticalPattern( selfHarmRisk == true, $score1 : score)
    DepressivePattern( severeDepressiveRisk == true, $score2 : score)
then
    insert(new FinalDecision(
        FinalState.SELF_HARM_RISK_PATTERN,
        Severity.CRITICAL,
        "Visok rizik od samopovređivanja.",
        "HITNA stručna intervencija.",
        List.of("SelfHarmRisk"), ($score1+$score2)/2.0
    ));
end
