package rules;
import com.ftn.sbnz.model.features.*;
import com.ftn.sbnz.model.risks.*;
//EMOTIONAL RISKS
rule "Emotional Stress Risk"
when
   EmotionalFeatures( $f : this )
    eval( ($f.getESI() >= 0.3 && $f.getESI() < 0.6)  || ($f.getNAI() >= 0.3 && $f.getNAI() < 0.6) )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalStressRisk(true);
    risk.setScore(($f.getESI() + $f.getNAI()) / 2.0);
    insert(risk);
end
rule "Emotional Overload Risk"
when
    EmotionalFeatures( $esi : ESI, $lci : LCI, ESI >= 0.6, LCI >= 0.3 && LCI < 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalOverloadRisk(true);
    risk.setScore(($esi + $lci) / 2.0);
    insert(risk);
end
rule "Emotional Instability Risk"
when
    EmotionalFeatures( $esi : ESI, $evi : EVI, ESI >= 0.6, EVI >= 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalInstabilityRisk(true);
    risk.setScore(($esi + $evi) / 2.0);
    insert(risk);
end
rule "Severe Emotional Crisis Risk"
when
    EmotionalFeatures( $esi : ESI, $nai : NAI, $lci : LCI, ESI >= 0.8, NAI >= 0.6, LCI >= 0.6 )
then
    EmotionalRisks risk = new EmotionalRisks();
    risk.setEmotionalCrisisRisk(true);
    risk.setScore(($esi + $nai + $lci) / 3.0);
    insert(risk);
end
//PHYSICAL RISKS
rule "Physical Fatigue Risk"
when
    SleepFeatures( $sqi : SQI, $fi : FI, FI >= 0.6, SQI < 0.3 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setPhysicalFatigueRisk(true);
    risk.setScore(($sqi + $fi) / 2.0);
    insert(risk);
end
rule "Exhaustion Syndrome Risk"
when
    SleepFeatures( $sqi : SQI, $sfi:SFI, $fi : FI,FI >= 0.6,
                      SFI >= 0.6,
                      SQI < 0.3 )
then
    PhysicalRisks risk = new PhysicalRisks();
    risk.setExhaustionRisk(true);
    risk.setScore(($sqi + $fi + $sfi) / 3.0);
    insert(risk);
end
//COGNITIVE RISKS
rule "Mental Fatigue Risk"
when
    CognitiveFeatures($mfs:MFS,
        MFS >= 0.6
    )
    SleepFeatures($fi: FI,
        FI >= 0.6
    )
then
    CognitiveRisks risk = new CognitiveRisks();
    risk.setMentalFatigueRisk(true);
    risk.setScore(($mfs + $fi) / 2.0);
    insert(risk);
end
//SOCIAL RISKS
rule "Behavioral Withdrawal Risk"
when
    SocialFeatures($sad:SAD,
        SAD >= 0.6
    )

    CognitiveFeatures($cli:CLI,
        CLI >= 0.6
    )
then
    SocialRisks risk = new SocialRisks();
    risk.setBehavioralWithdrawalRisk(true);
    risk.setScore(($sad + $cli) / 2.0);
    insert(risk);
end
//ENVIRONMENTAL RISKS
rule "External Pressure Risk"
when
    EnvironmentalFeatures($eSI:externalStressIndex,
        externalStressIndex >= 0.3 && externalStressIndex < 0.6
    )

    EmotionalFeatures($esi:ESI,
        ESI >= 0.3 && ESI < 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setExternalPressureRisk(true);
    risk.setScore(($eSI + $esi) / 2.0);
    insert(risk);
end

rule "High External Stress Risk"
when
    EnvironmentalFeatures($eSI:externalStressIndex,
        externalStressIndex >= 0.6
    )

    EmotionalFeatures($esi:ESI,
        ESI >= 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setHighExternalStressRisk(true);
    risk.setScore(($eSI + $esi) / 2.0);
    insert(risk);
end

rule "Chronic Stress Exposure Risk"
when
    EnvironmentalFeatures($cse:chronicStressExposure,
        chronicStressExposure >= 0.6
    )

    TemporalFeatures($sps:SPS,
        SPS >= 0.6
    )
then
    EnvironmentalRisks risk = new EnvironmentalRisks();
    risk.setChronicStressRisk(true);
    risk.setScore(($cse + $sps) / 2.0);
    insert(risk);
end
//TEMPORAL RISKS
rule "Emotional Instability Temporal Risk"
when
    TemporalFeatures($tii:TII,
        TII >= 0.6
    )

    EmotionalFeatures($evi:EVI,
        EVI >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setEmotionalInstabilityTemporalRisk(true);
    risk.setScore(($tii + $evi) / 2.0);
    insert(risk);
end

rule "Rapid Escalation Risk"
when
    TemporalFeatures($evl:EVL,
        EVL >= 0.6
    )

    EmotionalFeatures($esi:ESI,
        ESI >= 0.6
    )
then
    TemporalRisks risk = new TemporalRisks();
    risk.setEscalationRisk(true);
    risk.setScore(($evl+$esi) / 2.0);
    insert(risk);
end
